---
- hosts: node
  gather_facts: yes
  become: true
  tasks:

  - name: Download Node Exporter
    shell: |
      curl -SL https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-armv7.tar.gz > node_exporter.tar.gz
      tar -xvf node_exporter.tar.gz -C /usr/local/bin/ --strip-components=1
    args:
      chdir: /tmp

  - name: Copy node_exporter.service service file
    register: node_exporter_service
    template:
      src: "node_exporter.service"
      dest: "{{ systemd_dir }}/node_exporter.service"
      owner: root
      group: root
      mode: 0644

  - name: Enable and check K3s service
    systemd:
      name: node_exporter
      daemon_reload: yes
      state: restarted
      enabled: yes